name: Deploy Dashboard
on:
  push:
    branches:
      - main
      - development
jobs:
  deploy:
    uses: dfe-analytical-services/dfeshiny/.github/workflows/deploy_dashboard_template.yaml@develop
    with:
      parameter_file: deploy-parameters.yaml
      
