name: Deploy Dashboard
on:
  push:
    branches:
      - main
      - development
jobs:
  deploy:
    uses: dfe-analytical-services/dfeshiny/.github/workflows/dashboard_deploy_template.yaml@17-Deployment-yaml-template
    with:
      parameter_file: deploy-parameters.yaml
    secrets:
      SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
      
