name: Deploy Dashboard
on:
  push:
    branches:
      - main
      - development
jobs:
  deploy:
    uses: dfe-analytical-services/dfeshiny/.github/workflows/dashboard_deploy_template.yaml@docker-deploy-test
    with:
      parameter_file: deploy-parameters.yaml
      
